[package]
name = "rusty-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
# float-ord = "0.3.2"

[dependencies.eventual]
git = "https://github.com/carllerche/eventual"