[package]
name = "rusty-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
float-ord = "0.3.2"
tokio = { version = "1.27.0", features = ["full"] }